version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
volumes:
  pgdata:

  # api:
  #   build: .
  #   container_name: minha-api
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://usuario:senha@postgres:5432/nome-do-banco
